name: Zip and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          #body_path: CHANGELOG.md
          #body:
        env:
          TAG_NAME: release-${{ steps.date.outputs.date }}
          RELEASE_NAME: release-${{ steps.date.outputs.date }}
          GITHUB_TOKEN: ${{ github.token }}
          
      - id: step_upload_url
        name: Store Release upload URL for proceeding jobs
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

  publish_archive:
    name: Publish Extension Archive
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Extension Archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: 'src/*'
          filename: 'src_archive.zip'

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: extension.zip
          path: src_archive.zip

      - name: Upload Extension Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: src_archive.zip
          asset_name: extension.zip
          asset_content_type: application/zip

  publish_edge:
    name: Publish Extension to Edge Add-Ons Marketplace
    runs-on: ubuntu-latest
    needs: publish_archive
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: extension.zip
          path: src_archive.zip

      - uses: wdzeng/edge-addon@v1
        with:
          zip-path: src_archive.zip
          product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

  publish_chrome:
    name: Publish Extension to Chrome Web Store
    runs-on: ubuntu-latest
    needs: publish_archive
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: extension.zip
          path: src_archive.zip

      - uses: trmcnvn/chrome-addon@v2
        with:
          zip: src_archive.zip
          extension: ${{ secrets.CHROME_PRODUCT_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}